name: Automated task

on:
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate JSON and Markdown files
        run: |
          mkdir -p output
          themes_list=$(ls themes | sed 's/\..*$//' | jq -R . | jq -s .)
          echo $themes_list | jq . --indent 4 > list.json
          echo "# Themes" > themes.md
          ls themes | sed 's/\..*$/' | sed 's/^/- /' >> themes.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add list.json themes.md
          git commit -m "update: list" || echo "No changes to commit"
          git push

      - name: Delete all GitHub Pages deployments
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO_NAME=${{ github.repository }}
          page=1
          total_deleted=0
          while : ; do
            deployments=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_NAME/deployments?per_page=100&page=$page")
            deployment_count=$(echo "$deployments" | jq 'length')
            if [ "$deployment_count" -eq 0 ]; then
              break
            fi
            for deployment in $(echo "$deployments" | jq -r '.[].id'); do
              curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/$REPO_NAME/deployments/$deployment"
              total_deleted=$((total_deleted + 1))
            done
            page=$((page + 1))
          done
          echo "Total deployments deleted: $total_deleted"

      - name: Clean up GitHub Pages settings
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          REPO_NAME=${{ github.repository }}
          curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" -d '{"source": null}' "https://api.github.com/repos/$REPO_NAME/pages"
